version: '3.3'

services:
  db:
    image: postgres:10.3-alpine
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=catalog
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=pwd
    volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
